apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mlflow.fullname" . }}-env-secret
  labels:
    app: {{ template "mlflow.name" . }}
    chart: {{ template "mlflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
{{- if .Values.backendStore.postgres.enabled }}
  PGUSER: {{ required "postgres user must be specified" .Values.backendStore.postgres.user | b64enc }}
  PGPASSWORD: {{ required "postgres password must be specified" .Values.backendStore.postgres.password | b64enc }}
{{- end }}
{{- if .Values.backendStore.mysql.enabled }}
  MYSQL_USERNAME: {{ required "mysql user must be specified" .Values.backendStore.mysql.user | b64enc }}
  MYSQL_PWD: {{ required "mysql password must be specified" .Values.backendStore.mysql.password | b64enc }}
{{- end }}
{{- if .Values.artifactRoot.azureBlob.enabled }}
{{- if .Values.artifactRoot.azureBlob.connectionString }}
  AZURE_STORAGE_CONNECTION_STRING: {{ .Values.artifactRoot.azureBlob.connectionString | b64enc }}
{{- end }}
{{- if .Values.artifactRoot.azureBlob.accessKey }}
  AZURE_STORAGE_ACCESS_KEY: {{ .Values.artifactRoot.azureBlob.accessKey | b64enc }}
{{- end }}
{{- end }}
{{- if .Values.artifactRoot.s3.enabled }}
{{- if and .Values.artifactRoot.s3.awsAccessKeyId .Values.artifactRoot.s3.awsSecretAccessKey }}
  AWS_ACCESS_KEY_ID: {{ .Values.artifactRoot.s3.awsAccessKeyId | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.artifactRoot.s3.awsSecretAccessKey | b64enc }}
{{- end }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mlflow.fullname" . }}-auth-secret
  labels:
    app: {{ template "mlflow.name" . }}
    chart: {{ template "mlflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
  auth.ini: |
    [mlflow]
    default_permission={{ .Values.auth.defaultPermission | default "READ" }}
    database_uri={{ .Values.auth.databaseUri | default "" }}
    admin_username={{ .Values.auth.adminUsername | default "admin" }}
    admin_password={{ .Values.auth.adminPassword | default "password" }}
